# Generated by Django 3.0 on 2020-06-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='grade',
            new_name='section',
        ),
    ]
