# Generated by Django 3.0 on 2020-06-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200617_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
